### ISSUE TITLE
2. 提示原则 Guidelines.ipynb 的 Input [18] 应该是 in French summary 而非 in Italian summary

### ISSUE THREAD

**Issue by AntoineChn** [datawhalechina/prompt-engineering-for-developers#1]
# 对象
这个 issue 关于 Content 文件夹的 `2. 提示原则 Guidelines.ipynb`

# 问题描述
在 `2. 提示原则 Guidelines.ipynb` 的 In[18] 中写到

`Names: <list of names in Italian summary>`

然而, 这里仿佛应该是 `in French summary` 而非 `in Italian summary`

# 问题成因分析
官方 notebook 中这里的确也是 `in Italian summary`, 我倾向于认为, 这是官方视频 / 教学材料的疏忽.

# 行动建议

- 如果您认为这里 就应该是 `in Italian summary`, 那么可否讲一讲为什么 ? 是为了测试 ChapGPT 的反映么?
- 如果您同意我的看法, 认为这里写错了, 那么 我们要不要改过来?

**Comment by nowadays0421** [comment]
非常感谢您的建议，此处应是官方视频的疏忽，已修正该问题

**Comment by AntoineChn** [comment]
好的 ;-)
