### ISSUE TITLE
文档错误，env文件不应该写双引号

### ISSUE THREAD

**Issue by CanYang2000** [datawhalechina/prompt-engineering-for-developers#101]
文档：
https://github.com/datawhalechina/prompt-engineering-for-developers/blob/main/content/LangChain%20for%20LLM%20Application%20Development/2.模型、提示和解析器%20Models%2C%20Prompts%20and%20Output%20Parsers.ipynb

其中提到 .env文件格式为 OPENAI_API_KEY="your_key"，env文件不应该写双引号，正确应该是OPENAI_API_KEY=your_key

**Comment by longmarchw** [comment]
文件内的文字，是不用引号/双引号，代码里的才需要。

**Comment by nowadays0421** [comment]
引号“your_key”意为此处your_key是一个字符串；.env文件中带引号的key是可以使用的。
