### ISSUE TITLE
函数参数有误

### ISSUE THREAD

**Issue by longmarchw** [datawhalechina/prompt-engineering-for-developers#113]
7.检查结果 Check Outputs.ipynb 一文中，如下代码：
///
another_response = "生活就像一盒巧克力"
q_a_pair = f"""
顾客的信息: ```{customer_message}```
产品信息: ```{product_information}```
代理的回复: ```{final_response_to_customer}```
……
///
----------------------------代理的回复应该是：another_response，不是：final_response_to_customer。

**Comment by jiesns** [comment]
Traceback (most recent call last):
  File "/root/02.py", line 5, in <module>
    import tool
  File "/root/anaconda3/envs/chatgpt/lib/python3.9/site-packages/tool/__init__.py", line 11, in <module>
    from context_locals import app, local
ModuleNotFoundError: No module named 'context_locals'

**Comment by jiesns** [comment]
tool工具不能用？

**Comment by logan-zou** [comment]
已修正，感谢建议
