### ISSUE TITLE
HF_API_TTI_BASE and HF_API_TTI_BASE 

### ISSUE THREAD

**Issue by Chandler-Song** [datawhalechina/prompt-engineering-for-developers#119]
How to get HF_API_TTI_BASE and HF_API_TTI_BASE ，Could you please give a detailed instructions？ Thanks a lot.

**Comment by nowadays0421** [comment]
Hello, in this course, we've utilized a local model to replace the API, so there's no need for that key. For international learners, we recommend directly studying Professor Wu's original course.
