### ISSUE TITLE
Agent的翻译问题

### ISSUE THREAD

**Issue by thinkinds** [datawhalechina/prompt-engineering-for-developers#27]
[LangChain for LLM Application Development](https://github.com/datawhalechina/prompt-engineering-for-developers/tree/main/content/LangChain%20for%20LLM%20Application%20Development)第7节中的Agent翻成了”代理“，不是很妥。
![image](https://github.com/datawhalechina/prompt-engineering-for-developers/assets/12029093/45d7f945-6844-41c6-9204-6c723cef6eb1)

**Comment by nowadays0421** [comment]
收到反馈，非常感谢意见~不过目前我们对Agent的翻译一般都是普遍翻译为代理，之后我们会讨论一下相关情况，然后给出反馈修改，非常感谢~
