### ISSUE TITLE
吴恩达chatGPTapi构建系统第7课utils_zh.py

### ISSUE THREAD

**Issue by kuaitoukuai** [datawhalechina/prompt-engineering-for-developers#28]
Step 1: Input passed moderation check.
Traceback (most recent call last):

  File ~\Desktop\AI2023.3.30\查询openai的密码2023.6.6\吴恩达chaGPTAPI课程-7课英文版2023.6.6-1.py:109
    response,_ = process_user_message(user_input,[])

  File ~\Desktop\AI2023.3.30\查询openai的密码2023.6.6\吴恩达chaGPTAPI课程-7课英文版2023.6.6-1.py:47 in process_user_message
    category_and_product_response = utils_zh.find_category_and_product_only(user_input, utils_zh.get_products_and_category())

  File ~\Desktop\AI2023.3.30\查询openai的密码2023.6.6\utils_zh.py:159 in get_products_and_category
    products = get_products()

  File ~\Desktop\AI2023.3.30\查询openai的密码2023.6.6\utils_zh.py:170 in get_products
    with open(products_file, 'r') as file:

FileNotFoundError: [Errno 2] No such file or directory: 'products.json'

**Comment by nowadays0421** [comment]
已上传products.json，感谢反馈

**Comment by kuaitoukuai** [comment]
ok了，感谢 ，有没有相关的微信学习群呢
