### ISSUE TITLE
开一个吴恩达学习讨论微信群可以吗？

### ISSUE THREAD

**Issue by kuaitoukuai** [datawhalechina/prompt-engineering-for-developers#30]
![12f5a35d567efa06eb4746728df5075](https://github.com/datawhalechina/prompt-engineering-for-developers/assets/73692477/0cd85030-70c5-4e49-8f08-e47b4b593362)

**Comment by nowadays0421** [comment]
可以的，欢迎有需求有兴趣的小伙伴进群讨论学习~

**Comment by Xlu103** [comment]
大佬，群过期了
