### ISSUE TITLE
6.通用翻译器（openai每分钟只能请求3次）

### ISSUE THREAD

**Issue by KMnO4-zx** [datawhalechina/prompt-engineering-for-developers#8]
![image](https://github.com/datawhalechina/prompt-engineering-for-developers/assets/77671993/4a1e14ad-5282-4776-b086-1ec2a9c78e07)
这里会有一个报错如下：
> Rate limit reached for default-gpt-3.5-turbo in organization org-key on requests per min. Limit: 3 / min. Please try again in 20s. Contact us through our help center at help.openai.com if you continue to have issues. Please add a payment method to your account to increase your rate limit. Visit https://platform.openai.com/account/billing to add a payment method.

每分钟最多请求3次，不知道是不是新增加的限制。可以加个sleep。

**Comment by KMnO4-zx** [comment]
还有下面的综合语法检测，也有同样的问题
![image](https://github.com/datawhalechina/prompt-engineering-for-developers/assets/77671993/327ed7cc-b432-49f6-8bca-4e8c945dcdb3)

**Comment by nowadays0421** [comment]
已修正，感谢提醒!
